---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: frontend-ecommerce
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: IfNotPresent
        ports:
        - name: frontend
          containerPort: 80
     
