---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: default
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: IfNotPresent
        ports:
        - name: frontend
          containerPort: 80

