---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: test
  labels:
    app: front-end
  annotations:
    flux.weave.works/automated: 'true'
    # flux.weave.work/tag.front-end: glob:v2.0-*
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
    spec:
      containers:
      - name: front-end
        image: nitikornchumnankul/front-end:v2.0-573d865e
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
