---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: frontend
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 80
  selector:
    name: frontend
