variables:
  IMAGE_NAME: nitikornchumnankul/souvenir_frontend
  TAG: $CI_BUILD_REF

stages:
  - build
  - push
  - cleanup

build_production:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$TAG .
  only:
    - master

push_production:
  stage: build
  script:
    - docker push $IMAGE_NAME:$TAG
  only:
    - master

cleanup_production:
  stage: cleanup
  script:
    - docker rmi $( docker images | grep '<none>' | tr -s ' ' | cut -d ' ' -f 3)
  only:
    - master
  allow_failure: true
