language: node_js
sudo: required

node_js:
  - "node"
services:
   - docker

before_install:
   - sudo apt-get install -y make
  
  #  - make test-image deps
install:
  - npm install -D jest
  - npm install

env:
   - GROUP=nitikornchumnakul  COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG  REPO=canary-deployment-on-flagger-pipeline; YARN_GPG=no
before_script: 
  - cd  ./Application/backend
  - chmod 777 ./node_modules/.bin/jest
  - chmod 777 ./scripts/build.sh
  - chmod 777 ./scripts/push.sh
  
script:
  - npm test

after_success:
   - set -e
   - if [ -z "$DOCKER_PASSWORD" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
   - bash ./scripts/build.sh || travis_terminate 1;
   - bash ./scripts/push.sh  || travis_terminate 1;
notifications:
    slack: nitikornproject1:gdCBIXPs27fHWBz4Ymomk5JC

