language: node_js
sudo: required

node_js:
  - "node"
services:
   - docker

before_install:
   - sudo apt-get install -y make
  #  - make test-image deps
install:
  - npm install -D jest
  - npm install

env:
   - GROUP=nitikornchumnakul  COMMIT= ${TRAVIS_COMMIT}  TAG= ${TRAVIS_TAG} REPO=E-COMMERCE-AND-CANARY-DEPLOYMNET;
before_script: 
  - cd  ./e-commerce/backend
  - chmod 777 ./node_modules/.bin/jest
script:
  - npm test
  # - make test

after_success:
   - set -env
   - if [ -z "${DOCKER_PASS}" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
   - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
   - ./scripts/build.sh
   - ./scripts/push.sh
notifications:
    slack: nitikornproject1:gdCBIXPs27fHWBz4Ymomk5JC

