---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name:  front-end
  namespace: sut-kongtelalug
spec:
  scalRef:
    kind: Deployment
    name: front-end
    subresource: scale
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
    