---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  nginx
  labels:
    name: nginx
  namespace: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx:1.7.9
          containerPort: 8080
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
