---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: fortend
  annotations:
    flux.weave.works/locked_user: Nitikorn Chumnankul <pitchayapim1997@gmail.com>
    flux.weave.works/locked: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nitikornchumnankul/souvenir_frontend
        ports:
        - containerPort: 80
