apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  template:
    metadata:
    labels:
      name: front-end
    annotations:
      flux.weave.works/locked_user: Nitikorn Chumnankul <pitchayapim1997@gmail.com>
      flux.weave.works/automated: 'true'
    spec:
      containers:
        - name: front-end
          image: nitikornchumnankul/front-end
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name:  front-end
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4200
  selector:
    name:  front-end
