apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
   - port: 4200
     name: http
     targetPort: 4200
  selector:
    app: frontend 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: fortend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nitikornchumnankul/souvenir_frontend:v1
          ports:
            - containerPort: 4200
