FROM node:latest as node
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
RUN npm install sweetalert2
COPY . .
EXPOSE 4200
RUN npm start




# เก็บไว้ทำ multistage
#  FROM nginx:alpine
#  COPY --from=node /usr/src/app/public /usr/share/nginx/html

# COPY ./.nginx.conf /etc/nginx/conf.d/default.conf