apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: front-end
  namespace: test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-end
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: front-end
  service:
    port: 80
    targetPort: 80
    portName: http
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    hosts:
    - sut.kongtelalug.com
    trafficPolicy:
      tls:
        mode: DISABLE
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata: 
         cmd: "hey -z 1m -q 10 -c 2 http://front-end.test/"